.TH TASKER "1" "Jan 2022" "General Commands Manual"
.SH NAME
tasker \- a program that parallelizes tasks from a list on stdin
.SH SYNOPSIS
.B tasker command [command args]
.SH DESCRIPTION
Tasker is a program that takes a list from stdin and runs the given command
passing one line from stdin to the place designated by @@. It is kind of like
a xargs but parallelizes the jobs. It determines how many cores to use, sets
affinity to specific hyperthreads, and keeps all hyperthreads busy until the
input pipeline is complete.

The @@ is used to denote where to place the input from stdin into the
command to be executed. It can be a value to an argument, an insert to
an otherwise complete path name, or the only argument to the process to be
run.

It's purpose is intended to replace the

.RS
.EX
files=(ls /usr/lib64/*)
for f in files
do
       process $f
done
.EE
.RE

idiom. This can be rewritten as:

.RS
ls /usr/lib64/* | tasker process @@
.RE

where it will use all hyperthreads to quickly process the list.

.SH "SEE ALSO"
.BR htop(1)

.SH AUTHOR
Steve Grubb

